apiVersion: apps/v1
kind: Deployment
metadata:
  name: abysscore-backend
  namespace: abysscore
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: abysscore-backend
  template:
    metadata:
      labels:
        app: abysscore-backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: backend
        image: ghcr.io/bassmit12/abysscore-backend:99e20242841c2555db981ccffcd8a46c31fa6056
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: PORT
          value: "4000"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: KEYCLOAK_ISSUER
          value: "https://abysscore-auth.bassmit.dev/realms/abysscore"
        - name: KEYCLOAK_JWKS_URL
          value: "http://keycloak:8080/realms/abysscore/protocol/openid-connect/certs"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: abysscore-backend
  namespace: abysscore
  labels:
    app: abysscore-backend
spec:
  selector:
    app: abysscore-backend
  ports:
  - name: http
    port: 4000
    targetPort: 4000
