apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: abysscore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: cloudflared
        image: ghcr.io/bassmit12/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - $(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: token
