apiVersion: apps/v1
kind: Deployment
metadata:
  name: abysscore-frontend
  namespace: abysscore
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: abysscore-frontend
  template:
    metadata:
      labels:
        app: abysscore-frontend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: frontend
        image: ghcr.io/bassmit12/abysscore-frontend:99e20242841c2555db981ccffcd8a46c31fa6056
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: PORT
          value: "3000"
        - name: NEXTAUTH_URL
          value: "https://abysscore.bassmit.dev"
        - name: NEXTAUTH_SECRET
          value: "dev-secret-change-in-prod"
        - name: AUTH_SECRET
          value: "dev-secret-change-in-prod"
        - name: AUTH_TRUST_HOST
          value: "true"
        - name: KEYCLOAK_CLIENT_ID
          value: "abysscore-frontend"
        - name: KEYCLOAK_CLIENT_SECRET
          value: "abysscore-secret"
        - name: KEYCLOAK_ISSUER
          value: "https://abysscore-auth.bassmit.dev/realms/abysscore"
        - name: KEYCLOAK_WELL_KNOWN
          value: "http://keycloak:8080/realms/abysscore/.well-known/openid-configuration"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: abysscore-frontend
  namespace: abysscore
  labels:
    app: abysscore-frontend
spec:
  type: NodePort
  selector:
    app: abysscore-frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
