apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: abysscore
data:
  01-schemas.sql: |
    CREATE DATABASE combat OWNER abysscore;
    CREATE DATABASE deck OWNER abysscore;
    CREATE DATABASE dungeon OWNER abysscore;
    CREATE DATABASE game OWNER abysscore;
    CREATE DATABASE inventory OWNER abysscore;
    CREATE DATABASE leaderboard OWNER abysscore;
    CREATE DATABASE map OWNER abysscore;
  02-keycloak-db.sql: |
    SELECT 'CREATE DATABASE keycloak OWNER abysscore'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'keycloak')\gexec
